language: ruby
rvm:
  - "2.0.0"
  - "2.1.1"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database "abq-votes_test";' -U postgres
